services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: bed_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: bed_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data

  app:
    build: .
    restart: always
    depends_on:
      - db
      - minio
    ports:
      - "5001:5000"

volumes:
  pg_data:
  minio_data:
